CREATE TABLE player_stats (
    Player_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Gold_per_minute DECIMAL(5,2) NOT NULL,
    Winrate DECIMAL(5,2) NOT NULL,
    Counter_pickrate DECIMAL(5,2) NOT NULL,
    Kills INT NOT NULL,
    Deaths INT NOT NULL,
    Assists INT NOT NULL,
    Kda DECIMAL(5,2) NOT NULL,
    Kp DECIMAL(5,2) NOT NULL,
    Kill_share DECIMAL(5,2) NOT NULL,
    Share_team_deaths DECIMAL(5,2) NOT NULL,
    First_blood_rate DECIMAL(5,2) NOT NULL,
    Gold_diff_10 INT NOT NULL,
    Xp_diff_10 INT NOT NULL,
    Cs_diff_10 DECIMAL(5,2) NOT NULL,
    Cspm DECIMAL(5,2) NOT NULL,
    Share_team_deaths_15 DECIMAL(5,2) NOT NULL,
    Damage_per_minute INT NOT NULL,
    Share_damage DECIMAL(5,2) NOT NULL,
    Share_team_damage_15 DECIMAL(5,2) NOT NULL,
    Average_gold_per_minute INT NOT NULL,
    Gold_share DECIMAL(5,2) NOT NULL,
    Neutral_objectives_stolen INT NOT NULL,
    Wards_per_minute DECIMAL(5,2) NOT NULL,
    Control_wards_per_minute DECIMAL(5,2) NOT NULL,
    Wards_cleared_per_minute DECIMAL(5,2) NOT NULL,
    FOREIGN KEY (Player_ID) REFERENCES Players_information(Player_ID)
)COMMENT='Table storing information about players status.';

